# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Byeong-Ho Bahn
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme. 
baseurl: "" # the subpath of the site
url: "https://levbahn.github.io" # the base hostname & protocol for the site
og_image: /assets/img/main.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Introduction
      slug: /
    - name: Publications
    - name: Notes

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: bban@umass.edu
    - type: goos
      value: Google Scholar
      link: "https://scholar.google.com/citations?user=2p8u25UAAAAJ&hl=en"
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/byeong-ho-bahn-8a201716a/
    - type: github
      name: GitHub
      link: http://github.com/levbahn
 

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
